using System;
using System.Collections.Generic;
using System.Text;

namespace LayoutService.Enums
{
    public enum EnumProvedor
    {
        NaoDefinido = 0,
        SigCorpSigISS = 1,
        Ginfes = 2,
        DSF = 3,
        Paulistana = 4,
        Thema = 5,
        Metropolis = 6,
        BHISS = 7,
        WebISS = 8,
        EeL = 9,
        Goiania = 10,
        Conam = 11,
        Tiplan = 12,
        SMARAPD = 13,
        IssOnline = 14,
        Simpliss = 15,
        Natalense = 16,
        Fiorilli = 17,
        SuperNova = 18,
        Tinus = 19,
        GovDigital = 20,
        Simple = 21,
        SALVADOR_BA = 22,
        EGoverne = 23,
        SISPMJP = 24,
        BSITBR = 25,
        PRODATA = 26,
        Elotech = 27,
        CARIOCA = 28,
        Lexsom = 29,
        ABACO = 30,
        Coplan = 31,
        Betha = 32,
        IPM = 33,
        ISSnet = 34,
        PRONIM = 35,
        VersaTecnologia = 36,
        Bauru_SP = 37,
        DBSeller = 38,
        DSF_V3 = 39,
        JOINVILLE_SC = 40,
        MARINGA_PR = 41,
        CECAM = 42,
        Tiplan_203 = 43,
        Sintese = 44,
        RZL_INFORMATICA = 45,
        VVISS = 46,
        VITORIA_ES = 47,
        Megasoft = 48,
        WebISS_202 = 49,
        SIAT = 50,
        IssNet_202 = 51,
        IssOnline4R = 52,
        PORTALFACIL_ACTCON_202 = 53,
        ELv2 = 54,
        MANAUS_AM = 55,
        EReceita = 56
    }
}
